services:
  sasm-linux:
    #image: ghcr.io/keinenclue/sasm-docker
    build: 
      context: .
      dockerfile: Dockerfile.x64
    volumes:
      #- ./sasm:/root
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /tmp/.docker.xauth:/tmp/.docker.xauth
    environment:
      DISPLAY: ':0'
      XAUTHORITY: '/tmp/.docker.xauth'
  sasm-mac-win:
    # image: ghcr.io/keinenclue/sasm-docker
    build: .
    volumes:
      - ./sasm:/root
    environment:
      DISPLAY: 'host.docker.internal:0'
