on:
  push:
  workflow_dispatch:

name: Build Launcher

jobs:
  build:
    name: build
    strategy:
      matrix:
        go-version: [1.17.x]
        os: [ubuntu-18.04,windows-10,macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        shell: bash
        run: |
         if [ "$RUNNER_OS" == "Linux" ]; then
           DEBIAN_FRONTEND=noninteractive  sudo apt-get update
           DEBIAN_FRONTEND=noninteractive  sudo apt-get install -y libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev libgl1-mesa-dev
         fi
         go get fyne.io/fyne/v2/cmd/fyne
         go install fyne.io/fyne/v2/cmd/fyne

      - name: build
        shell: bash
        run: |
          cd launcher
          go build .

      - name: Copy artifacts
        run: |
          go build -o launcher-${RUNNER_OS}

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: launcher
          path: launcher-${{ env.RUNNER_OS }}
