on:
  push:
  workflow_dispatch:

name: Build Release

jobs:
  build:
    name: build
    strategy:
    matrix:
      go-version: [1.16.x]
      os: [ubuntu-18.04, macos-latest, windows-10]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
        go-version: '^1.17.2' # The Go version to download (if necessary) and use.

      - name: Install dependencies
        run: |
         go get fyne.io/fyne/v2/cmd/fyne
         go install fyne.io/fyne/v2/cmd/fyne
         fyne install

      - name: build
        run: |
          fyne package --sourceDir launcher

      - name: Copy artifacts
        run: mkdir dist && cp ./launcher* dist

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: dist/*